version: "3.8"
services:
  db:
    image: postgres:16.9
    container_name: customer_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgroot
      POSTGRES_DB: customer_microservice
    ports:
      - 5544:5432
